---
title: "Introduction to the Portfolio Project"
author: "Matthew Krachey"
date: 2021-09-04
categories: ["R"]
tags: ["R", "hugo"]
---

# Introduction

In this post we introduce the [American Statistical Association's (ASA)](https://www.amstat.org/) [Committee on Career Developments (CCD)](https://community.amstat.org/ccd/home) Portfolio project. The goal of this project is to make it easier for people to build their own personal portfolio website. In this first post we will lay out and explain the installation of an opinionated set of technology tools, as well as some advice in the best ways to effectively communicate technical skills in such a website. We will also provide some advice on how to use the website to add to your personal brand and link posts to social media to develop and maintain a good professional reputation. Read more about the Portfolio Project and our vision for it on the **About** page, linked in the menu. 
  
# Technologies we will be using and promoting

There is a very wide variety of potential blogging and website platforms, but the focus of the project is to be able to build a simple framework to communicate statistical, data science, and programming abilities rather than web development. As such, we chose a set of technologies that will make this the easiest, from our perspective. Further, most of these tools are based in or adjacent to the R statistical programming language, which should be familiar to most of the people who find themselves reading this, and engaging with CCD's Portfolio Project. Thus, the syntactic learning curve should hopefully be manageable. 

For reference, all of these tools are being used to build and maintain the Portfolio Project's website. Where possible, we will demonstrate (rather than merely explain) some best practices. Here's a list of what we recommend to at least get started:

  1. [R](https://www.r-project.org/) is free and open source. Many statisticians use it, so much of the code won't be foreign for a large number of readers. Most posts and content will focus on and around R, though at times we will bring in Python where is makes sense. 
  
  2. [RStudio](https://www.rstudio.com/) is the recommended IDE given clear integration with R, though any variety of choices here are perfectly great (e.g., PyCharm, Atom, VS Code, etc.).
  
  3. [Blogdown](https://pkgs.rstudio.com/blogdown/) is an R package that makes it extremely easy to create blog websites using [Rmarkdown](https://rmarkdown.rstudio.com/) and Hugo.
  
  4. [Hugo](https://gohugo.io/) is Go language based framework and is the target from `blogdown`. It facilitates building fast, static websites that support a lot of customization, and has many [user-built themes](https://themes.gohugo.io/). 
  
  5. [Netlify](https://www.netlify.com/) is a company that provides an easy and (for low volume sites) free hosting and deployment. Hence, we decided to keep the `.netlify.app` in our domain to demonstrate use and value of Netlify for similar projects and sites.
  
  6. [Github](https://github.com/) is a lightweight (no m,ajor dependency requirement) branch-based version control system for building and collaborating on a variety of code projects, including building sites like these. And it's free! Using Github to host your blog code, Netlify will automatically detect changes on the main branch, build and deploy the updated website very quickly.
  
# Initial steps

It is our goal to release new posts on a variety of topics with relatively common frequency. In the near term, we will focus on the initial installation process to get your site up and going. From there we will provide some examples, tips, guest posts etc to help you make the most out of your Portfolio site!
